/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPackage;

import LogicPackage.CatalogoGeneralObject;
import LogicPackage.Empresa;
import LogicPackage.Producto;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author joaom
 */
public class Catalogo_General extends javax.swing.JFrame {

    /**
     * Creates new form Catalogo_General
     */
    DefaultListModel<String> model;
    Empresa e;
    ArrayList<CatalogoGeneralObject> catalogo;
    
    public Catalogo_General() {
        initComponents();
    }
    
    public Catalogo_General(Empresa e, ArrayList<CatalogoGeneralObject> catalogo) {
        this.e = e;
        this.catalogo = catalogo;
        setTitle("Ventanas y Rejas José Cándido");
        initComponents();
        llenarProductos();
    }
    
    private void llenarProductos(){
        model = new DefaultListModel<>();
        
        for (CatalogoGeneralObject p1 : catalogo) {     
            
                model.addElement(p1.getProduto().getDescription() + " " + p1.getNombre());    
                
        }
        lListarCat.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bVolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lListarCat = new javax.swing.JList<>();
        bOrdenarFranquicia = new javax.swing.JButton();
        bOrdenarPrecio = new javax.swing.JButton();
        bVer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taVer = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Catalogo General");

        bVolver.setText("Volver");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lListarCat);

        bOrdenarFranquicia.setText("Ordenar Franquicia");
        bOrdenarFranquicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrdenarFranquiciaActionPerformed(evt);
            }
        });

        bOrdenarPrecio.setText("Ordenar Precio");
        bOrdenarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrdenarPrecioActionPerformed(evt);
            }
        });

        bVer.setText("Ver");
        bVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerActionPerformed(evt);
            }
        });

        taVer.setColumns(20);
        taVer.setRows(5);
        jScrollPane1.setViewportView(taVer);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bOrdenarFranquicia)
                        .addGap(18, 18, 18)
                        .addComponent(bOrdenarPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bVer, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(228, 228, 228))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bVolver)
                    .addComponent(bOrdenarFranquicia)
                    .addComponent(bOrdenarPrecio)
                    .addComponent(bVer))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        MainMenu m = new MainMenu(e);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bVolverActionPerformed

    private void bOrdenarFranquiciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrdenarFranquiciaActionPerformed
        model = new DefaultListModel<>();
        ArrayList<CatalogoGeneralObject> aux = catalogo;
        
        CatalogoGeneralObject tmp;
        
        for (int i = 0; i < aux.size(); i++) {

            for (int j = aux.size() - 1; j > i; j--) {
              
                if(aux.get(i).getNombre().compareTo(aux.get(j).getNombre())>0){

                  tmp = aux.get(i);
                  aux.set(i,aux.get(j));
                  aux.set(j,tmp);
                }
            } 
        }
        
        for (CatalogoGeneralObject p2 : aux) {     
            
                model.addElement(p2.getProduto().getDescription() + " " + p2.getNombre());    
                
        }
        lListarCat.setModel(model);
    }//GEN-LAST:event_bOrdenarFranquiciaActionPerformed

    private void bVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerActionPerformed
        int m = lListarCat.getSelectedIndex();
        
        if(lListarCat.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Tiene que elegir un Producto!", "Warning",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String precioVenta = String.valueOf(catalogo.get(m).getProduto().getPrecioVenta());
        String alto = String.valueOf(catalogo.get(m).getProduto().getAlto());
        String ancho = String.valueOf(catalogo.get(m).getProduto().getAncho());
        
        taVer.setText("Producto: " + catalogo.get(m).getProduto().getNombre() + 
                      "\n\nDescription: " + catalogo.get(m).getProduto().getDescription() + 
                      "\n\nPrecio: " + catalogo.get(m).getProduto().getPrecioVenta() + 
                      "\n\nAlto: " + catalogo.get(m).getProduto().getAlto() + 
                      "\n\nAncho: " + catalogo.get(m).getProduto().getAncho());
    }//GEN-LAST:event_bVerActionPerformed

    private void bOrdenarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrdenarPrecioActionPerformed
        
        ArrayList<CatalogoGeneralObject> aux = catalogo;
        model = new DefaultListModel<>();
       
        CatalogoGeneralObject tmp;
        
        for (int i = 0; i < aux.size(); i++) {

            for (int j = aux.size() - 1; j > i; j--) {
              
                if(aux.get(i).getProduto().getPrecioVenta() > aux.get(j).getProduto().getPrecioVenta()){

                  tmp = aux.get(i);
                  aux.set(i,aux.get(j));
                  aux.set(j,tmp);
                }
            } 
        }
        
        for (CatalogoGeneralObject p2 : aux) {     
            
                model.addElement(p2.getProduto().getDescription() + " " + p2.getNombre());    
                
        }
        lListarCat.setModel(model);
    }//GEN-LAST:event_bOrdenarPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogo_General().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOrdenarFranquicia;
    private javax.swing.JButton bOrdenarPrecio;
    private javax.swing.JButton bVer;
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lListarCat;
    private javax.swing.JTextArea taVer;
    // End of variables declaration//GEN-END:variables
}
