
package UIPackage;

import LogicPackage.Empresa;
import LogicPackage.Producto;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * @author João Piedade
 */
public class Cliente_ConsultarCatalogo extends javax.swing.JFrame {

    Empresa empresa;
    DefaultListModel<String> model;
    int id;
    
    /**
     * Creates new form Dueno_ConsultarCatalogo
     */
    public Cliente_ConsultarCatalogo() {
        initComponents();
        setTitle("Ventanas y Rejas José Cándido - Cliente");
    }
    
    public Cliente_ConsultarCatalogo(Empresa empresa, int id) {
        initComponents();
        setTitle("Ventanas y Rejas José Cándido - Cliente");
        this.empresa = empresa;
        this.id = id;
        lennarListaProductos();
    }

    private void lennarListaProductos(){
                        
        model = new DefaultListModel<>();

        for (Producto p : empresa.getFranquicias().get(id).getCatalogo().getListaProductos()){
            model.addElement(p.getDescription());
        }

        listProductos.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taListarProducto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        listProductos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        bVerProducto = new javax.swing.JButton();
        bVolver = new javax.swing.JButton();
        Balterar = new javax.swing.JButton();
        BComprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taListarProducto.setColumns(20);
        taListarProducto.setRows(5);
        jScrollPane1.setViewportView(taListarProducto);

        jScrollPane2.setViewportView(listProductos);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Catálogo");

        bVerProducto.setText("Ver");
        bVerProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerProductoActionPerformed(evt);
            }
        });

        bVolver.setText("Volver");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });

        Balterar.setText("Alterar");
        Balterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalterarActionPerformed(evt);
            }
        });

        BComprar.setText("Comprar");
        BComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bVerProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Balterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BComprar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(bVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bVolver)
                    .addComponent(bVerProducto)
                    .addComponent(Balterar)
                    .addComponent(BComprar))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVerProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerProductoActionPerformed
        
        int aux = listProductos.getSelectedIndex();
     
        if(listProductos.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Tiene que elegir un producto!", "Warning",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String precioVenta = String.valueOf(empresa.getFranquicias().get(id).getCatalogo().getListaProductos().get(aux).getPrecioVenta());
        String alto = String.valueOf(empresa.getFranquicias().get(id).getCatalogo().getListaProductos().get(aux).getAlto());
        String ancho = String.valueOf(empresa.getFranquicias().get(id).getCatalogo().getListaProductos().get(aux).getAncho());
        
        taListarProducto.setText("Producto: " + empresa.getFranquicias().get(id).getCatalogo().getListaProductos().get(aux).getNombre() + 
                                 "\n\nDrescription: " + empresa.getFranquicias().get(id).getCatalogo().getListaProductos().get(aux).getDescription() + 
                                 "\n\nPrecio: " + precioVenta + 
                                 "\n\nAlto: " + alto +
                                 "\n\nAncho: " + ancho);
        
        taListarProducto.setEditable(false);
       
    }//GEN-LAST:event_bVerProductoActionPerformed

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        Cliente_Menu c = new Cliente_Menu(empresa, id);
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bVolverActionPerformed

    private void BalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalterarActionPerformed
        int m = listProductos.getSelectedIndex();
        
        if(listProductos.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Tiene que elegir un producto!", "Warning",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Producto p = empresa.getFranquicias().get(id).getCatalogo().getListaProductos().get(m);
        
        if(p.getNombre().equalsIgnoreCase("Pieza") || p.getNombre().equalsIgnoreCase("pieza")){
            JOptionPane.showMessageDialog(null, "Lo producto elegido no puede ser cambiado!", "Warning",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
            
        Cliente_ModificarProducto d = new Cliente_ModificarProducto(empresa, empresa.getFranquicias().get(id).getCatalogo().getListaProductos().get(m), id);
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BalterarActionPerformed

    private void BComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BComprarActionPerformed
        int m = listProductos.getSelectedIndex();
         
        if(listProductos.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Tiene que elegir un producto!", "Warning",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(empresa.getFranquicias().get(id).getCatalogo().getListaProductos().get(m).getNombre().equalsIgnoreCase("Pieza")  && empresa.getFranquicias().get(id).getCatalogo().getListaProductos().get(m).getNombre().equalsIgnoreCase("pieza") )
        {
            empresa.getFranquicias().get(id).getCompras().add(empresa.getFranquicias().get(id).getCatalogo().getListaProductos().get(m));
            Cliente_Compras g = new Cliente_Compras(empresa, id);
            g.setVisible(true);
            this.dispose();
        }else
        {
            Trabajador_DesejaInstalacion c = new Trabajador_DesejaInstalacion(empresa, id, empresa.getFranquicias().get(id).getCatalogo().getListaProductos().get(m));
            c.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_BComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente_ConsultarCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente_ConsultarCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente_ConsultarCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente_ConsultarCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente_ConsultarCatalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BComprar;
    private javax.swing.JButton Balterar;
    private javax.swing.JButton bVerProducto;
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listProductos;
    private javax.swing.JTextArea taListarProducto;
    // End of variables declaration//GEN-END:variables
}
